typing ignore: dymaic typing of dwarfinfo
`dwarfinfo` depends on the ELF/DWARF format analysed are *runtime*, as
such the type is not static:

> elftools/dwarf/ranges.py:51: error: Cannot determine type of "dwarfinfo"  [has-type]
> elftools/dwarf/ranges.py:52: error: Cannot determine type of "dwarfinfo"  [has-type]
> elftools/dwarf/locationlists.py:66: error: Cannot determine type of "dwarfinfo"  [has-type]
> elftools/dwarf/locationlists.py:67: error: Cannot determine type of "dwarfinfo"  [has-type]

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>