test: Fix missing testlog
```console
$ cd test && python3 all_tests.py
Traceback (most recent call last):
  File "…/pyelftools/test/all_tests.py", line 29, in <module>
    sys.exit(main())
             ^^^^^^
  File "…/pyelftools/test/all_tests.py", line 21, in main
    testlog.error('Error: Please run me from the root dir of pyelftools!')
    ^^^^^^^
NameError: name 'testlog' is not defined
```

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>