Fix architecture specific dump
`get_section_by_name()` might return `None` in case architecture
specific dumping is requested:

```console
$ scripts/readelf.py --arch-specific test/testfiles_for_unittests/arm_with_form_indirect.elf
…
Traceback (most recent call last):
  File "scripts/readelf.py", line 1986, in <module>
    main()
  File "scripts/readelf.py", line 1956, in main
    readelf.display_arch_specific()
  File "scripts/readelf.py", line 800, in display_arch_specific
    self._display_arch_specific_arm()
  File "scripts/readelf.py", line 1832, in _display_arch_specific_arm
    self._display_attributes(attr_sec, describe_attr_tag_arm)
  File "scripts/readelf.py", line 1818, in _display_attributes
    for s in attr_sec.iter_subsections():
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'iter_subsections'
```

Fixes: 906f28610b7b ("ARM build attributes section parsing (#160)")
Fixes: 43e77712efde ("Add support for RISC-V attributes (#459)")
Signed-off-by: Philipp Hahn <phahn-oss@avm.de>