Fix running tests (#598)
* test: Fix missing testlog

```console
$ cd test && python3 all_tests.py
Traceback (most recent call last):
  File "…/pyelftools/test/all_tests.py", line 29, in <module>
    sys.exit(main())
             ^^^^^^
  File "…/pyelftools/test/all_tests.py", line 21, in main
    testlog.error('Error: Please run me from the root dir of pyelftools!')
    ^^^^^^^
NameError: name 'testlog' is not defined
```

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>

* test: Run test with locale C

Otherwise the output of `readelf` might be translated and comparison
with the English output from `readelf.py` will fail.

```console
$ LC_ALL=de_DE.UTF-8 ./test/run_readelf_tests.py
Test file 'test/testfiles_for_readelf/aarch64-pac-bti.elf'
.......................FAIL
....for file test/testfiles_for_readelf/aarch64-pac-bti.elf
....for option "-e"
....Output #1 is readelf, Output #2 is pyelftools
@@ Mismatch on line #0:
>>elf-header:<<
>>elf header:<<
 ([('equal', 0, 3, 0, 3), ('replace', 3, 4, 3, 4), ('equal', 4, 11, 4, 11)])
```

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>

---------

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>